name: water_1024smpl_seed1_fthead
seed: 1
work_dir: /leonardo_work/IIT24_AtomSim/franken/rebuttal/mace_finetune/water_1024smpl_seed1_fthead/
downloads_dir: /leonardo_scratch/fast/IIT24_AtomSim/franken/franken_cache/

# Validation & test sets are the same. Note that the datasets have been rewritten from the original ones
# to have the keys for energy and forces which are expected from MACE (REF_energy and REF_forces instead of
# just energy and forces).
train_file: /leonardo_scratch/fast/IIT24_AtomSim/franken/franken_cache/water/train_1024_seed1.xyz
valid_file: /leonardo_scratch/fast/IIT24_AtomSim/franken/franken_cache/water/water_val.xyz
test_file: /leonardo_scratch/fast/IIT24_AtomSim/franken/franken_cache/water/water_val.xyz
energy_key: REF_energy
forces_key: REF_forces

foundation_model: small #/leonardo_scratch/fast/IIT24_AtomSim/franken/franken_cache/gnn_checkpoints/mace/2023-12-10-mace-128-L0_energy_epoch-249.model

E0s: "{1: -5.865928644991999, 8: -2.9329643224959985}"      # equal to "average" with whole dataset
lr: 0.001           # default
energy_weight: 1    # default
forces_weight: 100  # default
stress_weight: 0
dipole_weight: 0
batch_size: 16
max_num_epochs: 10  # total of 640 steps
ema: true
ema_decay: 0.9  # reduced from default 0.99. Might need to disable for small datasets
amsgrad: true
default_dtype: float64
device: cuda

ft_readout_only: true
multiheads_finetuning: false
